import { NodeDefinition, NodeLibrary } from "../types";

const defineNode = (node: NodeDefinition): NodeDefinition => node;

const sourceNodes: NodeDefinition[] = [
  defineNode({
    id: "source-image",
    name: "Image Source",
    description:
      "Loads raster images and exposes them as image payloads for downstream nodes.",
    category: "source",
    lane: "data",
    maturity: "mvp",
    inputs: [],
    outputs: [
      {
        id: "image",
        label: "ImageData",
        kind: "ImageData",
        required: true,
      },
    ],
    parameters: [
      {
        id: "file",
        label: "File",
        type: "text",
        description: "File input or drag-and-drop handle.",
      },
      {
        id: "resizeMode",
        label: "Resize Mode",
        type: "enum",
        defaultValue: "fit",
        options: [
          { label: "Fit", value: "fit" },
          { label: "Fill", value: "fill" },
          { label: "Stretch", value: "stretch" },
          { label: "None", value: "none" },
        ],
        description: "How to adapt the loaded image to the working resolution.",
      },
      {
        id: "preserveAspect",
        label: "Preserve Aspect Ratio",
        type: "boolean",
        defaultValue: true,
      },
      {
        id: "colorProfile",
        label: "Color Profile",
        type: "enum",
        defaultValue: "sRGB",
        options: [
          { label: "sRGB", value: "sRGB" },
          { label: "Display P3", value: "DisplayP3" },
          { label: "Linear", value: "linear" },
        ],
        description: "Optional color profile conversion.",
      },
    ],
    tags: ["raster", "import"],
  }),
  defineNode({
    id: "source-wav",
    name: "WAV Source",
    description: "Loads .wav files and exposes decoded audio signals.",
    category: "source",
    lane: "data",
    maturity: "mvp",
    inputs: [],
    outputs: [
      {
        id: "audio",
        label: "AudioSignal",
        kind: "AudioSignal",
        required: true,
      },
    ],
    parameters: [
      {
        id: "file",
        label: "File",
        type: "text",
        description: "File reference for WAV input.",
      },
      {
        id: "channel",
        label: "Channel Mode",
        type: "enum",
        defaultValue: "stereo",
        options: [
          { label: "Mono Sum", value: "mono" },
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
          { label: "Stereo", value: "stereo" },
        ],
      },
      {
        id: "window",
        label: "Sample Window",
        type: "number",
        defaultValue: 1,
        min: 0.1,
        max: 60,
        unit: "s",
      },
      {
        id: "normalize",
        label: "Normalize Gain",
        type: "boolean",
        defaultValue: true,
      },
    ],
    tags: ["audio", "import"],
  }),
  defineNode({
    id: "source-noise",
    name: "Noise Source",
    description: "Generates procedural scalar fields such as Perlin or Worley noise.",
    category: "source",
    lane: "data",
    maturity: "mvp",
    inputs: [],
    outputs: [
      {
        id: "field",
        label: "ScalarField",
        kind: "ScalarField",
        required: true,
      },
    ],
    parameters: [
      { id: "width", label: "Width", type: "integer", defaultValue: 720 },
      { id: "height", label: "Height", type: "integer", defaultValue: 720 },
      { id: "seed", label: "Seed", type: "text", defaultValue: "plotter" },
      { id: "scale", label: "Scale", type: "number", defaultValue: 200, min: 1 },
      { id: "octaves", label: "Octaves", type: "integer", defaultValue: 4, min: 1, max: 8 },
      { id: "lacunarity", label: "Lacunarity", type: "number", defaultValue: 2 },
      { id: "persistence", label: "Persistence", type: "number", defaultValue: 0.5, min: 0, max: 1 },
      { id: "offsetX", label: "Offset X", type: "number", defaultValue: 0 },
      { id: "offsetY", label: "Offset Y", type: "number", defaultValue: 0 },
    ],
    variants: ["Perlin", "Simplex", "FBM", "Ridged", "Cellular"],
    tags: ["procedural", "field"],
  }),
  defineNode({
    id: "source-constant-field",
    name: "Constant Field",
    description: "Outputs a flat scalar field useful for testing, blending, or masks.",
    category: "source",
    lane: "data",
    maturity: "second-wave",
    inputs: [],
    outputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    parameters: [
      { id: "value", label: "Value", type: "number", defaultValue: 0.5, min: 0, max: 1 },
      { id: "width", label: "Width", type: "integer", defaultValue: 1024, min: 64 },
      { id: "height", label: "Height", type: "integer", defaultValue: 1024, min: 64 },
      { id: "resolution", label: "Resolution", type: "integer", defaultValue: 1024, min: 64 },
    ],
    tags: ["utility", "field"],
  }),
  defineNode({
    id: "source-gradient-field",
    name: "Gradient Field",
    description: "Generates linear, radial, or conical gradients as scalar fields.",
    category: "source",
    lane: "data",
    maturity: "second-wave",
    inputs: [],
    outputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    parameters: [
      {
        id: "mode",
        label: "Type",
        type: "enum",
        defaultValue: "linear",
        options: [
          { label: "Linear", value: "linear" },
          { label: "Radial", value: "radial" },
          { label: "Conical", value: "conical" },
        ],
      },
      { id: "direction", label: "Direction", type: "number", defaultValue: 0, unit: "deg" },
      { id: "centerX", label: "Center X", type: "number", defaultValue: 0.5 },
      { id: "centerY", label: "Center Y", type: "number", defaultValue: 0.5 },
      { id: "falloff", label: "Falloff", type: "number", defaultValue: 1, min: 0.1, max: 4 },
    ],
    tags: ["field", "procedural"],
  }),
  defineNode({
    id: "source-shape",
    name: "Shape Source",
    description: "Outputs analytic shapes as masks or polylines for clipping/compositing.",
    category: "source",
    lane: "data",
    maturity: "advanced",
    inputs: [],
    outputs: [
      { id: "mask", label: "Mask", kind: "Mask", required: false },
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: false },
    ],
    parameters: [
      {
        id: "shape",
        label: "Shape",
        type: "enum",
        defaultValue: "circle",
        options: [
          { label: "Circle", value: "circle" },
          { label: "Rectangle", value: "rectangle" },
          { label: "Polygon", value: "polygon" },
          { label: "Star", value: "star" },
        ],
      },
      { id: "size", label: "Size", type: "number", defaultValue: 200 },
      { id: "rotation", label: "Rotation", type: "number", defaultValue: 0, unit: "deg" },
      { id: "position", label: "Position", type: "vector2", defaultValue: { x: 0.5, y: 0.5 } },
    ],
    tags: ["mask", "geometry", "procedural"],
  }),
  defineNode({
    id: "source-text",
    name: "Text Source",
    description: "Converts text into vector outlines or masks for typography workflows.",
    category: "source",
    lane: "data",
    maturity: "advanced",
    inputs: [],
    outputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: false },
      { id: "mask", label: "Mask", kind: "Mask", required: false },
    ],
    parameters: [
      { id: "text", label: "Text", type: "text" },
      { id: "font", label: "Font", type: "text" },
      { id: "size", label: "Font Size", type: "number", defaultValue: 48 },
      {
        id: "alignment",
        label: "Alignment",
        type: "enum",
        defaultValue: "left",
        options: [
          { label: "Left", value: "left" },
          { label: "Center", value: "center" },
          { label: "Right", value: "right" },
          { label: "Justify", value: "justify" },
        ],
      },
    ],
    tags: ["typography", "vector"],
  }),
  defineNode({
    id: "source-random-points",
    name: "Random Points Source",
    description:
      "Generates random, jittered, or Poisson distributions for stippling and Voronoi workflows.",
    category: "source",
    lane: "data",
    maturity: "second-wave",
    inputs: [],
    outputs: [
      { id: "points", label: "PointSet", kind: "PointSet", required: true },
    ],
    parameters: [
      { id: "count", label: "Count", type: "integer", defaultValue: 500, min: 1 },
      { id: "seed", label: "Seed", type: "text", defaultValue: "points" },
      {
        id: "distribution",
        label: "Distribution",
        type: "enum",
        defaultValue: "uniform",
        options: [
          { label: "Uniform", value: "uniform" },
          { label: "Jittered Grid", value: "jittered" },
          { label: "Poisson Disk", value: "poisson" },
        ],
      },
      { id: "bounds", label: "Bounds", type: "vector2", description: "Area dimensions or extents." },
    ],
    tags: ["points", "procedural"],
  }),
];

const conversionNodes: NodeDefinition[] = [
  defineNode({
    id: "convert-image-grayscale",
    name: "Image to Grayscale Field",
    description: "Converts raster luminance into a scalar field for contouring workflows.",
    category: "conversion",
    lane: "data",
    maturity: "mvp",
    inputs: [
      { id: "image", label: "Image", kind: "ImageData", required: true, description: "Source image." },
    ],
    outputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    parameters: [
      { id: "weights", label: "Luminance Weights", type: "text", description: "RGB weighting triplet such as 0.299/0.587/0.114." },
      { id: "invert", label: "Invert", type: "boolean", defaultValue: false },
      { id: "gamma", label: "Gamma", type: "number", defaultValue: 1, min: 0.1, max: 4 },
      { id: "contrast", label: "Contrast", type: "number", defaultValue: 1, min: 0.1, max: 4 },
    ],
    tags: ["image", "field"],
  }),
  defineNode({
    id: "convert-image-channel",
    name: "Image Channel Extract",
    description: "Extracts R, G, B, A, hue, saturation, or value channels as scalar fields.",
    category: "conversion",
    lane: "data",
    maturity: "second-wave",
    inputs: [
      { id: "image", label: "Image", kind: "ImageData", required: true },
    ],
    outputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    parameters: [
      {
        id: "channel",
        label: "Channel",
        type: "enum",
        defaultValue: "luminance",
        options: [
          { label: "Red", value: "r" },
          { label: "Green", value: "g" },
          { label: "Blue", value: "b" },
          { label: "Alpha", value: "a" },
          { label: "Hue", value: "hue" },
          { label: "Saturation", value: "saturation" },
          { label: "Value", value: "value" },
          { label: "Luminance", value: "luminance" },
        ],
      },
      { id: "normalize", label: "Normalize", type: "boolean", defaultValue: true },
    ],
    tags: ["image", "field"],
  }),
  defineNode({
    id: "convert-image-edge",
    name: "Image to Edge Field",
    description: "Computes edge intensity maps for outlines and contour seeding.",
    category: "conversion",
    lane: "data",
    maturity: "second-wave",
    inputs: [
      { id: "image", label: "Image", kind: "ImageData", required: true },
    ],
    outputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    parameters: [
      {
        id: "operator",
        label: "Edge Operator",
        type: "enum",
        defaultValue: "sobel",
        options: [
          { label: "Sobel", value: "sobel" },
          { label: "Scharr", value: "scharr" },
          { label: "Canny", value: "canny" },
        ],
      },
      { id: "blur", label: "Blur Amount", type: "number", defaultValue: 1, min: 0, max: 10 },
      { id: "thresholdBias", label: "Threshold Bias", type: "number", defaultValue: 0.5, min: 0, max: 1 },
    ],
    tags: ["image", "edges"],
  }),
  defineNode({
    id: "convert-audio-envelope",
    name: "Audio to Envelope",
    description: "Creates amplitude envelopes from raw audio signals.",
    category: "conversion",
    lane: "data",
    maturity: "mvp",
    inputs: [
      { id: "audio", label: "Audio", kind: "AudioSignal", required: true },
    ],
    outputs: [
      { id: "envelope", label: "Envelope", kind: "EnvelopeData", required: true },
    ],
    parameters: [
      { id: "window", label: "Window Size", type: "number", defaultValue: 0.01, min: 0.001, max: 1, unit: "s" },
      { id: "smoothing", label: "Smoothing", type: "number", defaultValue: 0.5, min: 0, max: 1 },
      { id: "attack", label: "Attack", type: "number", defaultValue: 0.1, min: 0, max: 1 },
      { id: "release", label: "Release", type: "number", defaultValue: 0.3, min: 0, max: 1 },
    ],
    tags: ["audio", "analysis"],
  }),
  defineNode({
    id: "convert-audio-spectrum",
    name: "Audio to Spectrum",
    description: "Runs FFT analysis to produce spectrogram data.",
    category: "conversion",
    lane: "data",
    maturity: "mvp",
    inputs: [
      { id: "audio", label: "Audio", kind: "AudioSignal", required: true },
    ],
    outputs: [
      { id: "spectrum", label: "SpectrumData", kind: "SpectrumData", required: true },
    ],
    parameters: [
      { id: "fftSize", label: "FFT Size", type: "integer", defaultValue: 2048, min: 256, max: 16384 },
      { id: "overlap", label: "Overlap", type: "number", defaultValue: 0.5, min: 0, max: 0.95 },
      {
        id: "window",
        label: "Window Function",
        type: "enum",
        defaultValue: "hann",
        options: [
          { label: "Hann", value: "hann" },
          { label: "Hamming", value: "hamming" },
          { label: "Blackman", value: "blackman" },
        ],
      },
      {
        id: "scale",
        label: "Scale",
        type: "enum",
        defaultValue: "linear",
        options: [
          { label: "Linear", value: "linear" },
          { label: "Log", value: "log" },
        ],
      },
    ],
    tags: ["audio", "spectrum"],
  }),
  defineNode({
    id: "convert-spectrum-field",
    name: "Spectrum to Scalar Field",
    description: "Converts spectrogram frames into scalar fields for contour tools.",
    category: "conversion",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "spectrum", label: "Spectrum", kind: "SpectrumData", required: true },
    ],
    outputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    parameters: [
      { id: "timeScale", label: "Time Scaling", type: "number", defaultValue: 1, min: 0.1, max: 10 },
      { id: "frequencyScale", label: "Frequency Scaling", type: "number", defaultValue: 1, min: 0.1, max: 10 },
      { id: "normalize", label: "Normalize", type: "boolean", defaultValue: true },
      { id: "logFrequency", label: "Log Frequency", type: "boolean", defaultValue: false },
    ],
    tags: ["audio", "field"],
  }),
  defineNode({
    id: "convert-geometry-mask",
    name: "Geometry to Mask",
    description: "Rasterizes vector shapes into masks for clipping and compositing.",
    category: "conversion",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true },
    ],
    outputs: [
      { id: "mask", label: "Mask", kind: "Mask", required: true },
    ],
    parameters: [
      { id: "resolution", label: "Resolution", type: "integer", defaultValue: 2048, min: 128 },
      {
        id: "mode",
        label: "Fill Mode",
        type: "enum",
        defaultValue: "fill",
        options: [
          { label: "Fill", value: "fill" },
          { label: "Outline", value: "outline" },
        ],
      },
      { id: "antialias", label: "Antialiasing", type: "boolean", defaultValue: true },
    ],
    tags: ["geometry", "mask"],
  }),
  defineNode({
    id: "convert-mask-field",
    name: "Mask to Field",
    description: "Normalizes mask data into scalar fields for blending and contouring.",
    category: "conversion",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "mask", label: "Mask", kind: "Mask", required: true },
    ],
    outputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    parameters: [
      { id: "invert", label: "Invert", type: "boolean", defaultValue: false },
      { id: "normalize", label: "Normalize", type: "boolean", defaultValue: true },
    ],
    tags: ["mask", "field"],
  }),
];
const fieldNodes: NodeDefinition[] = [
  defineNode({
    id: "field-normalize",
    name: "Normalize Field",
    description: "Rescales field values to a target range.",
    category: "field",
    lane: "data",
    maturity: "mvp",
    inputs: [
      { id: "field", label: "Field", kind: "ScalarField", required: true },
    ],
    outputs: [
      { id: "normalized", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    parameters: [
      { id: "min", label: "Output Min", type: "number", defaultValue: 0 },
      { id: "max", label: "Output Max", type: "number", defaultValue: 1 },
      { id: "clamp", label: "Clamp Input", type: "boolean", defaultValue: true },
      { id: "auto", label: "Auto Normalize", type: "boolean", defaultValue: true },
    ],
  }),
  defineNode({
    id: "field-invert",
    name: "Invert Field",
    description: "Flips scalar field values.",
    category: "field",
    lane: "data",
    maturity: "second-wave",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "inverted", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [],
  }),
  defineNode({
    id: "field-bias-gain",
    name: "Bias / Gain Field",
    description: "Applies bias/gain curves for contrast shaping.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "shaped", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "bias", label: "Bias", type: "number", defaultValue: 0.5, min: 0, max: 1 },
      { id: "gain", label: "Gain", type: "number", defaultValue: 0.5, min: 0, max: 1 },
    ],
  }),
  defineNode({
    id: "field-levels",
    name: "Levels / Threshold Field",
    description: "Quantizes or thresholds scalar fields.",
    category: "field",
    lane: "data",
    maturity: "mvp",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [
      { id: "fieldOut", label: "ScalarField", kind: "ScalarField", required: false },
      { id: "maskOut", label: "Mask", kind: "Mask", required: false },
    ],
    parameters: [
      { id: "min", label: "Min", type: "number", defaultValue: 0, min: 0, max: 1 },
      { id: "max", label: "Max", type: "number", defaultValue: 1, min: 0, max: 1 },
      { id: "bands", label: "Bands", type: "integer", defaultValue: 4, min: 1, max: 32 },
      {
        id: "mode",
        label: "Mode",
        type: "enum",
        defaultValue: "quantize",
        options: [
          { label: "Quantize", value: "quantize" },
          { label: "Threshold", value: "threshold" },
        ],
      },
    ],
  }),
  defineNode({
    id: "field-blur",
    name: "Blur Field",
    description: "Applies Gaussian-style blur for smoother contours.",
    category: "field",
    lane: "data",
    maturity: "mvp",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "blurred", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "radius", label: "Radius", type: "number", defaultValue: 3, min: 0, max: 100 },
      { id: "sigma", label: "Sigma", type: "number", defaultValue: 1, min: 0.1, max: 20 },
      { id: "iterations", label: "Iterations", type: "integer", defaultValue: 1, min: 1, max: 10 },
    ],
  }),
  defineNode({
    id: "field-sharpen",
    name: "Sharpen Field",
    description: "Enhances structure after blur or edge extraction.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "sharpened", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "amount", label: "Amount", type: "number", defaultValue: 1, min: 0, max: 5 },
      { id: "threshold", label: "Threshold", type: "number", defaultValue: 0.1, min: 0, max: 1 },
    ],
  }),
  defineNode({
    id: "field-resample",
    name: "Resample Field",
    description: "Changes resolution for performance or quality.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "resampled", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "width", label: "Width", type: "integer", defaultValue: 1024, min: 16 },
      { id: "height", label: "Height", type: "integer", defaultValue: 1024, min: 16 },
      {
        id: "interpolation",
        label: "Interpolation",
        type: "enum",
        defaultValue: "bilinear",
        options: [
          { label: "Nearest", value: "nearest" },
          { label: "Bilinear", value: "bilinear" },
          { label: "Bicubic", value: "bicubic" },
        ],
      },
    ],
  }),
  defineNode({
    id: "field-crop",
    name: "Crop Field",
    description: "Extracts a subregion for compositional control.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "cropped", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "x", label: "X", type: "number", defaultValue: 0 },
      { id: "y", label: "Y", type: "number", defaultValue: 0 },
      { id: "width", label: "Width", type: "number", defaultValue: 512 },
      { id: "height", label: "Height", type: "number", defaultValue: 512 },
    ],
  }),
  defineNode({
    id: "field-blend",
    name: "Blend Fields",
    description: "Combines two scalar fields with blend modes.",
    category: "field",
    lane: "data",
    maturity: "mvp",
    inputs: [
      { id: "a", label: "Field A", kind: "ScalarField", required: true },
      { id: "b", label: "Field B", kind: "ScalarField", required: true },
    ],
    outputs: [{ id: "result", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      {
        id: "mode",
        label: "Blend Mode",
        type: "enum",
        defaultValue: "add",
        options: [
          { label: "Add", value: "add" },
          { label: "Subtract", value: "subtract" },
          { label: "Multiply", value: "multiply" },
          { label: "Screen", value: "screen" },
          { label: "Min", value: "min" },
          { label: "Max", value: "max" },
          { label: "Average", value: "average" },
        ],
      },
    ],
  }),
  defineNode({
    id: "field-remap",
    name: "Remap Field",
    description: "Applies custom curves/splines to values.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "remapped", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "curve", label: "Curve", type: "text", description: "Serialized spline/curve definition." },
    ],
  }),
  defineNode({
    id: "field-clamp",
    name: "Clamp Field",
    description: "Restricts values to a given range.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "clamped", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "min", label: "Min", type: "number", defaultValue: 0 },
      { id: "max", label: "Max", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "field-displace",
    name: "Displace Field",
    description: "Warps one field using another as displacement map.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "source", label: "Source Field", kind: "ScalarField", required: true },
      { id: "displacement", label: "Displacement Field", kind: "ScalarField", required: true },
    ],
    outputs: [{ id: "displaced", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "strength", label: "Strength", type: "number", defaultValue: 20 },
      { id: "scaleX", label: "Scale X", type: "number", defaultValue: 1 },
      { id: "scaleY", label: "Scale Y", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "field-domain-warp",
    name: "Domain Warp",
    description: "Warps field coordinates via another field or vector field.",
    category: "field",
    lane: "data",
    maturity: "second-wave",
    inputs: [
      { id: "field", label: "Field", kind: "ScalarField", required: true },
      { id: "warpField", label: "Warp Field", kind: "ScalarField", required: false },
      { id: "warpVector", label: "Warp Vector", kind: "VectorField", required: false },
    ],
    outputs: [{ id: "warped", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "amount", label: "Warp Amount", type: "number", defaultValue: 30 },
      { id: "tiling", label: "Coordinate Scale", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "field-distance-transform",
    name: "Distance Transform",
    description: "Generates distance fields from masks.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "mask", label: "Mask", kind: "Mask", required: true }],
    outputs: [{ id: "distance", label: "DistanceField", kind: "DistanceField", required: true }],
    parameters: [
      { id: "invert", label: "Invert Mask", type: "boolean", defaultValue: false },
      { id: "normalize", label: "Normalize", type: "boolean", defaultValue: true },
    ],
  }),
  defineNode({
    id: "field-mosaic",
    name: "Mosaic / Posterize Field",
    description: "Reduces detail into larger zones for plotter-friendly output.",
    category: "field",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "field", label: "Field", kind: "ScalarField", required: true }],
    outputs: [{ id: "posterized", label: "ScalarField", kind: "ScalarField", required: true }],
    parameters: [
      { id: "blockSize", label: "Block Size", type: "integer", defaultValue: 8, min: 1, max: 256 },
      { id: "quantization", label: "Levels", type: "integer", defaultValue: 5, min: 1, max: 32 },
    ],
  }),
];
const vectorFieldNodes: NodeDefinition[] = [
  defineNode({
    id: "vector-noise",
    name: "Noise Vector Field",
    description: "Generates directional vector fields from noise for flow lines and warping.",
    category: "vectorField",
    lane: "data",
    maturity: "advanced",
    inputs: [],
    outputs: [{ id: "vector", label: "VectorField", kind: "VectorField", required: true }],
    parameters: [
      { id: "seed", label: "Seed", type: "text", defaultValue: "flow" },
      { id: "scale", label: "Scale", type: "number", defaultValue: 200, min: 1 },
      {
        id: "mapping",
        label: "Angle Mapping",
        type: "enum",
        defaultValue: "full",
        options: [
          { label: "0-360°", value: "full" },
          { label: "0-180°", value: "half" },
          { label: "Custom Curve", value: "curve" },
        ],
      },
    ],
  }),
  defineNode({
    id: "vector-gradient",
    name: "Gradient Vector Field",
    description: "Derives vector directions from scalar field slopes.",
    category: "vectorField",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "field", label: "ScalarField", kind: "ScalarField", required: true }],
    outputs: [{ id: "vector", label: "VectorField", kind: "VectorField", required: true }],
    parameters: [
      { id: "normalize", label: "Normalize", type: "boolean", defaultValue: true },
      { id: "strength", label: "Strength", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "vector-curl",
    name: "Curl Field",
    description: "Builds curl-like flow from scalar/noise inputs.",
    category: "vectorField",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: false },
      { id: "seed", label: "Seed", kind: "Seed", required: false },
    ],
    outputs: [{ id: "vector", label: "VectorField", kind: "VectorField", required: true }],
    parameters: [
      { id: "scale", label: "Scale", type: "number", defaultValue: 150 },
      { id: "strength", label: "Strength", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "vector-normalize",
    name: "Normalize Vector Field",
    description: "Normalizes vector magnitudes to unit length.",
    category: "vectorField",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "vector", label: "VectorField", kind: "VectorField", required: true }],
    outputs: [{ id: "normalized", label: "VectorField", kind: "VectorField", required: true }],
    parameters: [],
  }),
  defineNode({
    id: "vector-scale",
    name: "Scale Vector Field",
    description: "Adjusts vector magnitudes.",
    category: "vectorField",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "vector", label: "VectorField", kind: "VectorField", required: true }],
    outputs: [{ id: "scaled", label: "VectorField", kind: "VectorField", required: true }],
    parameters: [
      { id: "scale", label: "Scale", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "vector-rotate",
    name: "Rotate Vector Field",
    description: "Applies global rotation to vectors.",
    category: "vectorField",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "vector", label: "VectorField", kind: "VectorField", required: true }],
    outputs: [{ id: "rotated", label: "VectorField", kind: "VectorField", required: true }],
    parameters: [
      { id: "angle", label: "Angle", type: "number", defaultValue: 0, unit: "deg" },
    ],
  }),
  defineNode({
    id: "vector-blend",
    name: "Blend Vector Fields",
    description: "Combines multiple directional systems.",
    category: "vectorField",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "a", label: "Vector A", kind: "VectorField", required: true },
      { id: "b", label: "Vector B", kind: "VectorField", required: true },
    ],
    outputs: [{ id: "result", label: "VectorField", kind: "VectorField", required: true }],
    parameters: [
      { id: "mix", label: "Mix", type: "number", defaultValue: 0.5, min: 0, max: 1 },
    ],
  }),
  defineNode({
    id: "vector-mask",
    name: "Mask Vector Field",
    description: "Restricts vectors to mask regions.",
    category: "vectorField",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "vector", label: "VectorField", kind: "VectorField", required: true },
      { id: "mask", label: "Mask", kind: "Mask", required: true },
    ],
    outputs: [{ id: "masked", label: "VectorField", kind: "VectorField", required: true }],
    parameters: [],
  }),
];
const audioNodes: NodeDefinition[] = [
  defineNode({
    id: "audio-channel-selector",
    name: "Channel Selector",
    description: "Chooses audio channel combinations (left/right/mono/difference).",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "audio", label: "Audio", kind: "AudioSignal", required: true }],
    outputs: [{ id: "selected", label: "Audio", kind: "AudioSignal", required: true }],
    parameters: [
      {
        id: "mode",
        label: "Mode",
        type: "enum",
        defaultValue: "mono",
        options: [
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
          { label: "Mono Sum", value: "mono" },
          { label: "Difference", value: "difference" },
        ],
      },
    ],
  }),
  defineNode({
    id: "audio-trim",
    name: "Trim Audio",
    description: "Cuts audio to a specified time range.",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "audio", label: "Audio", kind: "AudioSignal", required: true }],
    outputs: [{ id: "trimmed", label: "Audio", kind: "AudioSignal", required: true }],
    parameters: [
      { id: "start", label: "Start", type: "number", defaultValue: 0, unit: "s" },
      { id: "end", label: "End", type: "number", defaultValue: 10, unit: "s" },
    ],
  }),
  defineNode({
    id: "audio-resample",
    name: "Resample Audio",
    description: "Changes sample rate for performance or clarity.",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "audio", label: "Audio", kind: "AudioSignal", required: true }],
    outputs: [{ id: "resampled", label: "Audio", kind: "AudioSignal", required: true }],
    parameters: [
      { id: "sampleRate", label: "Sample Rate", type: "integer", defaultValue: 44100 },
    ],
  }),
  defineNode({
    id: "audio-smooth",
    name: "Smooth Audio",
    description: "Applies moving average or low-pass filtering.",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "audio", label: "Audio", kind: "AudioSignal", required: true }],
    outputs: [{ id: "smoothed", label: "Audio", kind: "AudioSignal", required: true }],
    parameters: [
      { id: "window", label: "Window", type: "integer", defaultValue: 5, min: 1 },
      { id: "mode", label: "Mode", type: "enum", defaultValue: "moving-average", options: [
        { label: "Moving Average", value: "moving-average" },
        { label: "Low-pass", value: "lowpass" },
      ] },
    ],
  }),
  defineNode({
    id: "audio-normalize",
    name: "Normalize Audio",
    description: "Rescales amplitude for consistent downstream behavior.",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "audio", label: "Audio", kind: "AudioSignal", required: true }],
    outputs: [{ id: "normalized", label: "Audio", kind: "AudioSignal", required: true }],
    parameters: [
      { id: "target", label: "Target Level", type: "number", defaultValue: -1, unit: "dBFS" },
    ],
  }),
  defineNode({
    id: "audio-detect-peaks",
    name: "Detect Peaks",
    description: "Extracts beats or transient markers.",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "audio", label: "Audio", kind: "AudioSignal", required: false },
      { id: "envelope", label: "Envelope", kind: "EnvelopeData", required: false },
    ],
    outputs: [
      { id: "points", label: "PointSet", kind: "PointSet", required: true },
    ],
    parameters: [
      { id: "threshold", label: "Threshold", type: "number", defaultValue: 0.6, min: 0, max: 1 },
      { id: "minDistance", label: "Min Distance", type: "number", defaultValue: 0.2, unit: "s" },
    ],
  }),
  defineNode({
    id: "audio-spectrogram-builder",
    name: "Spectrogram Builder",
    description: "Generates SpectrumData with controllable resolution.",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "audio", label: "Audio", kind: "AudioSignal", required: true }],
    outputs: [{ id: "spectrum", label: "SpectrumData", kind: "SpectrumData", required: true }],
    parameters: [
      { id: "fftSize", label: "FFT Size", type: "integer", defaultValue: 1024 },
      { id: "hopSize", label: "Hop Size", type: "integer", defaultValue: 256 },
      { id: "window", label: "Window", type: "enum", defaultValue: "hann", options: [
        { label: "Hann", value: "hann" },
        { label: "Hamming", value: "hamming" },
        { label: "Blackman", value: "blackman" },
      ] },
    ],
  }),
  defineNode({
    id: "audio-band-split",
    name: "Band Splitter",
    description: "Separates low/mid/high bands into envelopes or fields.",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [{ id: "spectrum", label: "Spectrum", kind: "SpectrumData", required: true }],
    outputs: [
      { id: "low", label: "Low Envelope", kind: "EnvelopeData", required: false },
      { id: "mid", label: "Mid Envelope", kind: "EnvelopeData", required: false },
      { id: "high", label: "High Envelope", kind: "EnvelopeData", required: false },
    ],
    parameters: [
      { id: "lowCut", label: "Low Cut", type: "number", defaultValue: 200, unit: "Hz" },
      { id: "highCut", label: "High Cut", type: "number", defaultValue: 4000, unit: "Hz" },
      { id: "mode", label: "Output Mode", type: "enum", defaultValue: "envelope", options: [
        { label: "Envelope", value: "envelope" },
        { label: "Field", value: "field" },
      ] },
    ],
  }),
  defineNode({
    id: "audio-modulation",
    name: "Audio to Modulation Signal",
    description: "Produces normalized control signals for parameter driving.",
    category: "audio",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "audio", label: "Audio", kind: "AudioSignal", required: false },
      { id: "envelope", label: "Envelope", kind: "EnvelopeData", required: false },
    ],
    outputs: [{ id: "mod", label: "EnvelopeData", kind: "EnvelopeData", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "envelope", options: [
        { label: "Envelope", value: "envelope" },
        { label: "RMS", value: "rms" },
        { label: "Peak", value: "peak" },
      ] },
      { id: "normalize", label: "Normalize", type: "boolean", defaultValue: true },
    ],
  }),
];
const geometryNodes: NodeDefinition[] = [
  defineNode({
    id: "geometry-contours",
    name: "Contour Generator",
    description: "Extracts isolines from scalar fields.",
    category: "geometry",
    lane: "geometry",
    maturity: "mvp",
    inputs: [{ id: "field", label: "ScalarField", kind: "ScalarField", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "levels", label: "Contour Levels", type: "integer", defaultValue: 8, min: 1, max: 64 },
      { id: "rangeMin", label: "Level Min", type: "number", defaultValue: 0 },
      { id: "rangeMax", label: "Level Max", type: "number", defaultValue: 1 },
      { id: "closed", label: "Closed Loops", type: "boolean", defaultValue: true },
      { id: "smoothing", label: "Smoothing", type: "number", defaultValue: 0.2, min: 0, max: 1 },
      { id: "minLoop", label: "Min Loop Size", type: "number", defaultValue: 5 },
    ],
  }),
  defineNode({
    id: "geometry-iso-bands",
    name: "Iso-Band Generator",
    description: "Produces filled contour bands or boundary rings.",
    category: "geometry",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "field", label: "ScalarField", kind: "ScalarField", required: true }],
    outputs: [
      { id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: false },
      { id: "layers", label: "LayeredGeometry", kind: "LayeredGeometry", required: false },
    ],
    parameters: [
      { id: "bands", label: "Bands", type: "integer", defaultValue: 6, min: 1, max: 32 },
      { id: "rangeMin", label: "Min", type: "number", defaultValue: 0 },
      { id: "rangeMax", label: "Max", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "geometry-edge-trace",
    name: "Edge Trace",
    description: "Converts edge fields into vector paths.",
    category: "geometry",
    lane: "geometry",
    maturity: "second-wave",
    inputs: [
      { id: "image", label: "Image", kind: "ImageData", required: false },
      { id: "field", label: "ScalarField", kind: "ScalarField", required: false },
    ],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "threshold", label: "Threshold", type: "number", defaultValue: 0.5, min: 0, max: 1 },
      { id: "joinDistance", label: "Join Distance", type: "number", defaultValue: 4 },
      { id: "simplify", label: "Simplify", type: "number", defaultValue: 2 },
    ],
  }),
  defineNode({
    id: "geometry-waveform",
    name: "Waveform Renderer",
    description: "Maps audio samples to polyline geometry.",
    category: "geometry",
    lane: "geometry",
    maturity: "mvp",
    inputs: [
      { id: "audio", label: "Audio", kind: "AudioSignal", required: false },
      { id: "envelope", label: "Envelope", kind: "EnvelopeData", required: false },
    ],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "linear", options: [
        { label: "Linear", value: "linear" },
        { label: "Stacked", value: "stacked" },
        { label: "Radial", value: "radial" },
        { label: "Spiral", value: "spiral" },
      ] },
      { id: "sampleDensity", label: "Sample Density", type: "integer", defaultValue: 1500 },
      { id: "amplitude", label: "Amplitude", type: "number", defaultValue: 0.85 },
      { id: "smoothing", label: "Smoothing", type: "number", defaultValue: 0.3 },
    ],
  }),
  defineNode({
    id: "geometry-spectral-contour",
    name: "Spectral Contour Renderer",
    description: "Builds lines from spectrogram data.",
    category: "geometry",
    lane: "geometry",
    maturity: "second-wave",
    inputs: [
      { id: "spectrum", label: "Spectrum", kind: "SpectrumData", required: false },
      { id: "field", label: "ScalarField", kind: "ScalarField", required: false },
    ],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "contours", label: "Contours", type: "integer", defaultValue: 12 },
      { id: "timeScale", label: "Time Scale", type: "number", defaultValue: 1 },
      { id: "frequencyScale", label: "Frequency Scale", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "geometry-flow-lines",
    name: "Flow Line Generator",
    description: "Traces lines through vector fields.",
    category: "geometry",
    lane: "geometry",
    maturity: "advanced",
    inputs: [
      { id: "vector", label: "VectorField", kind: "VectorField", required: true },
      { id: "seeds", label: "Seed Points", kind: "PointSet", required: false },
    ],
    outputs: [{ id: "flow", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "stepSize", label: "Step Size", type: "number", defaultValue: 4 },
      { id: "lineLength", label: "Line Length", type: "number", defaultValue: 400 },
      { id: "seedCount", label: "Seed Count", type: "integer", defaultValue: 200 },
      { id: "collision", label: "Collision Mode", type: "enum", defaultValue: "stop", options: [
        { label: "Stop", value: "stop" },
        { label: "Wrap", value: "wrap" },
      ] },
    ],
  }),
  defineNode({
    id: "geometry-hatch",
    name: "Hatch Generator",
    description: "Creates hatch lines from fields or masks.",
    category: "geometry",
    lane: "geometry",
    maturity: "second-wave",
    inputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: false },
      { id: "mask", label: "Mask", kind: "Mask", required: false },
      { id: "vector", label: "VectorField", kind: "VectorField", required: false },
    ],
    outputs: [{ id: "hatch", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "spacing", label: "Spacing", type: "number", defaultValue: 10 },
      { id: "angle", label: "Angle", type: "number", defaultValue: 45 },
      { id: "cross", label: "Crosshatch", type: "boolean", defaultValue: false },
      { id: "density", label: "Density Mapping", type: "enum", defaultValue: "linear", options: [
        { label: "Linear", value: "linear" },
        { label: "Exponential", value: "exp" },
      ] },
    ],
  }),
  defineNode({
    id: "geometry-stipple",
    name: "Stipple Generator",
    description: "Creates dot/point distributions based on fields.",
    category: "geometry",
    lane: "geometry",
    maturity: "advanced",
    inputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: false },
      { id: "mask", label: "Mask", kind: "Mask", required: false },
    ],
    outputs: [{ id: "points", label: "PointSet", kind: "PointSet", required: true }],
    parameters: [
      { id: "count", label: "Count", type: "integer", defaultValue: 2000 },
      { id: "threshold", label: "Threshold", type: "number", defaultValue: 0.5 },
    ],
  }),
  defineNode({
    id: "geometry-point-connect",
    name: "Point Connect / TSP Lines",
    description: "Connects point sets into single or multi-line sequences.",
    category: "geometry",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "points", label: "PointSet", kind: "PointSet", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "nearest", options: [
        { label: "Nearest Neighbor", value: "nearest" },
        { label: "TSP Approx", value: "tsp" },
        { label: "Spiral", value: "spiral" },
      ] },
    ],
  }),
  defineNode({
    id: "geometry-voronoi",
    name: "Voronoi / Delaunay Generator",
    description: "Builds graph structures from points.",
    category: "geometry",
    lane: "geometry",
    maturity: "second-wave",
    inputs: [{ id: "points", label: "PointSet", kind: "PointSet", required: true }],
    outputs: [{ id: "graph", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "voronoi", options: [
        { label: "Voronoi", value: "voronoi" },
        { label: "Delaunay", value: "delaunay" },
        { label: "Dual", value: "dual" },
      ] },
      { id: "relaxations", label: "Relaxations", type: "integer", defaultValue: 0 },
    ],
  }),
  defineNode({
    id: "geometry-medial",
    name: "Medial Line / Skeletonize",
    description: "Extracts centerlines from masks.",
    category: "geometry",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "mask", label: "Mask", kind: "Mask", required: true }],
    outputs: [{ id: "skeleton", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "prune", label: "Prune Length", type: "number", defaultValue: 5 },
    ],
  }),
  defineNode({
    id: "geometry-grid",
    name: "Grid / Lattice Generator",
    description: "Builds structured line systems for composition.",
    category: "geometry",
    lane: "geometry",
    maturity: "advanced",
    inputs: [],
    outputs: [{ id: "grid", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "columns", label: "Columns", type: "integer", defaultValue: 6 },
      { id: "rows", label: "Rows", type: "integer", defaultValue: 6 },
      { id: "mode", label: "Mode", type: "enum", defaultValue: "rect", options: [
        { label: "Rectilinear", value: "rect" },
        { label: "Isometric", value: "iso" },
        { label: "Radial", value: "radial" },
      ] },
    ],
  }),
];
const pathNodes: NodeDefinition[] = [
  defineNode({
    id: "path-simplify",
    name: "Simplify Paths",
    description: "Reduces point count using Douglas-Peucker style simplification.",
    category: "path",
    lane: "geometry",
    maturity: "mvp",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "tolerance", label: "Tolerance", type: "number", defaultValue: 1.2 },
      { id: "preserveCorners", label: "Preserve Corners", type: "boolean", defaultValue: true },
    ],
  }),
  defineNode({
    id: "path-smooth",
    name: "Smooth Paths",
    description: "Applies smoothing filters to polylines.",
    category: "path",
    lane: "geometry",
    maturity: "mvp",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "window", label: "Window", type: "integer", defaultValue: 3, min: 1, max: 25 },
      { id: "strength", label: "Strength", type: "number", defaultValue: 0.5 },
    ],
  }),
  defineNode({
    id: "path-resample",
    name: "Resample Paths",
    description: "Redistributes points at even spacing.",
    category: "path",
    lane: "geometry",
    maturity: "second-wave",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "resampled", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "spacing", label: "Spacing", type: "number", defaultValue: 2 },
    ],
  }),
  defineNode({
    id: "path-trim",
    name: "Trim Paths",
    description: "Cuts polylines by length, bounds, or parameter ranges.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "trimmed", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "length", options: [
        { label: "Length", value: "length" },
        { label: "Bounds", value: "bounds" },
        { label: "Percentage", value: "percent" },
      ] },
      { id: "start", label: "Start", type: "number", defaultValue: 0 },
      { id: "end", label: "End", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "path-split",
    name: "Split Paths",
    description: "Splits long or self-crossing lines into manageable pieces.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "splits", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "maxLength", label: "Max Length", type: "number", defaultValue: 500 },
    ],
  }),
  defineNode({
    id: "path-merge",
    name: "Merge Paths",
    description: "Joins nearby endpoints within tolerance.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "merged", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "tolerance", label: "Tolerance", type: "number", defaultValue: 5 },
    ],
  }),
  defineNode({
    id: "path-reverse",
    name: "Reverse Paths",
    description: "Flips line direction.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "reversed", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [],
  }),
  defineNode({
    id: "path-offset",
    name: "Offset Paths",
    description: "Creates parallel curves for stylization or compensation.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "offset", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "distance", label: "Distance", type: "number", defaultValue: 5 },
      { id: "side", label: "Side", type: "enum", defaultValue: "both", options: [
        { label: "Left", value: "left" },
        { label: "Right", value: "right" },
        { label: "Both", value: "both" },
      ] },
    ],
  }),
  defineNode({
    id: "path-warp",
    name: "Path Warp",
    description: "Distorts geometry using scalar or vector fields.",
    category: "path",
    lane: "geometry",
    maturity: "second-wave",
    inputs: [
      { id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true },
      { id: "field", label: "ScalarField", kind: "ScalarField", required: false },
      { id: "vector", label: "VectorField", kind: "VectorField", required: false },
    ],
    outputs: [{ id: "warped", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "strength", label: "Strength", type: "number", defaultValue: 20 },
      { id: "mode", label: "Mode", type: "enum", defaultValue: "field-normal", options: [
        { label: "Field Normal", value: "field-normal" },
        { label: "Field Tangent", value: "field-tangent" },
        { label: "Vector", value: "vector" },
      ] },
    ],
  }),
  defineNode({
    id: "path-jitter",
    name: "Jitter Paths",
    description: "Adds controlled noise for hand-drawn feel.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "jittered", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "amplitude", label: "Amplitude", type: "number", defaultValue: 2 },
      { id: "frequency", label: "Frequency", type: "number", defaultValue: 0.5 },
    ],
  }),
  defineNode({
    id: "path-clip",
    name: "Clip Paths",
    description: "Cuts geometry by masks or other polylines.",
    category: "path",
    lane: "geometry",
    maturity: "mvp",
    inputs: [
      { id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true },
      { id: "clipperMask", label: "Mask", kind: "Mask", required: false },
      { id: "clipperPaths", label: "PolylineSet", kind: "PolylineSet", required: false },
    ],
    outputs: [{ id: "clipped", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "inside", options: [
        { label: "Inside", value: "inside" },
        { label: "Outside", value: "outside" },
      ] },
    ],
  }),
  defineNode({
    id: "path-boolean",
    name: "Boolean Paths",
    description: "Performs union/intersection/difference operations.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [
      { id: "a", label: "A", kind: "PolylineSet", required: true },
      { id: "b", label: "B", kind: "PolylineSet", required: true },
    ],
    outputs: [{ id: "result", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "union", options: [
        { label: "Union", value: "union" },
        { label: "Intersect", value: "intersect" },
        { label: "Difference", value: "difference" },
      ] },
    ],
  }),
  defineNode({
    id: "path-dash",
    name: "Dash / Segment Paths",
    description: "Converts continuous paths into dashed segments.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "dashed", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "pattern", label: "Pattern", type: "text", defaultValue: "10,5" },
      { id: "phase", label: "Phase", type: "number", defaultValue: 0 },
    ],
  }),
  defineNode({
    id: "path-close-open",
    name: "Close / Open Paths",
    description: "Toggles loop status explicitly.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "modified", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "close", options: [
        { label: "Close", value: "close" },
        { label: "Open", value: "open" },
      ] },
    ],
  }),
  defineNode({
    id: "path-dedupe",
    name: "Dedupe Paths",
    description: "Removes duplicates or overlapping segments.",
    category: "path",
    lane: "geometry",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "deduped", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "tolerance", label: "Tolerance", type: "number", defaultValue: 0.5 },
    ],
  }),
];
const optimizationNodes: NodeDefinition[] = [
  defineNode({
    id: "opt-remove-fragments",
    name: "Remove Tiny Fragments",
    description: "Deletes very short lines to reduce noise.",
    category: "optimization",
    lane: "plot",
    maturity: "mvp",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "minLength", label: "Minimum Length", type: "number", defaultValue: 5 },
    ],
  }),
  defineNode({
    id: "opt-sort-paths",
    name: "Sort Paths",
    description: "Reorders paths to reduce pen travel.",
    category: "optimization",
    lane: "plot",
    maturity: "mvp",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "strategy", label: "Strategy", type: "enum", defaultValue: "nearest", options: [
        { label: "Nearest Neighbor", value: "nearest" },
        { label: "Greedy", value: "greedy" },
        { label: "Layer Aware", value: "layer" },
      ] },
    ],
  }),
  defineNode({
    id: "opt-orient-paths",
    name: "Optimize Directions",
    description: "Flips path directions for lower travel.",
    category: "optimization",
    lane: "plot",
    maturity: "mvp",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [],
  }),
  defineNode({
    id: "opt-join-endpoints",
    name: "Join Nearby Endpoints",
    description: "Auto-merges paths within a tolerance.",
    category: "optimization",
    lane: "plot",
    maturity: "mvp",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "joined", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "tolerance", label: "Tolerance", type: "number", defaultValue: 3 },
    ],
  }),
  defineNode({
    id: "opt-remove-overlaps",
    name: "Remove Overlaps",
    description: "Detects and prunes duplicate geometry.",
    category: "optimization",
    lane: "plot",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "clean", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "tolerance", label: "Tolerance", type: "number", defaultValue: 0.25 },
    ],
  }),
  defineNode({
    id: "opt-travel-estimator",
    name: "Travel Estimator",
    description: "Outputs stats about travel distance/time.",
    category: "optimization",
    lane: "plot",
    maturity: "second-wave",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [
      { id: "pathsOut", label: "PolylineSet", kind: "PolylineSet", required: true },
      { id: "stats", label: "Metadata", kind: "PlotDocument", required: false, description: "Stores stats in document metadata." },
    ],
    parameters: [
      { id: "penUpSpeed", label: "Pen-up Speed", type: "number", defaultValue: 300, unit: "mm/s" },
      { id: "penDownSpeed", label: "Pen-down Speed", type: "number", defaultValue: 120, unit: "mm/s" },
    ],
  }),
  defineNode({
    id: "opt-pen-lift",
    name: "Pen Lift Minimizer",
    description: "Composite optimizer focusing on pen lifts.",
    category: "optimization",
    lane: "plot",
    maturity: "advanced",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "optimized", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "iterations", label: "Iterations", type: "integer", defaultValue: 4 },
    ],
  }),
  defineNode({
    id: "opt-plotter-safe",
    name: "Plotter Safe Filter",
    description: "Applies a preset cleanup (remove fragments, simplify, merge, sort).",
    category: "optimization",
    lane: "plot",
    maturity: "second-wave",
    inputs: [{ id: "paths", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "safe", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "profile", label: "Profile", type: "enum", defaultValue: "default", options: [
        { label: "Default", value: "default" },
        { label: "Speed", value: "speed" },
        { label: "Quality", value: "quality" },
      ] },
    ],
  }),
];
const layoutNodes: NodeDefinition[] = [
  defineNode({
    id: "layout-transform",
    name: "Transform Geometry",
    description: "Applies translate/scale/rotate transforms.",
    category: "layout",
    lane: "plot",
    maturity: "mvp",
    inputs: [{ id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "transformed", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "translate", label: "Translate", type: "vector2", defaultValue: { x: 0, y: 0 } },
      { id: "scale", label: "Scale", type: "vector2", defaultValue: { x: 1, y: 1 } },
      { id: "rotation", label: "Rotation", type: "number", defaultValue: 0, unit: "deg" },
    ],
  }),
  defineNode({
    id: "layout-scale-to-page",
    name: "Scale to Page",
    description: "Fits geometry to paper presets with margins.",
    category: "layout",
    lane: "plot",
    maturity: "mvp",
    inputs: [{ id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "page", label: "Page Preset", type: "enum", defaultValue: "letter-portrait", options: [
        { label: "Letter Portrait", value: "letter-portrait" },
        { label: "Letter Landscape", value: "letter-landscape" },
        { label: "A4 Portrait", value: "a4-portrait" },
        { label: "A4 Landscape", value: "a4-landscape" },
      ] },
      { id: "margin", label: "Margin", type: "number", defaultValue: 10, unit: "mm" },
      { id: "align", label: "Align", type: "enum", defaultValue: "center", options: [
        { label: "Center", value: "center" },
        { label: "Top Left", value: "top-left" },
        { label: "Top Right", value: "top-right" },
        { label: "Bottom Left", value: "bottom-left" },
        { label: "Bottom Right", value: "bottom-right" },
      ] },
      { id: "preserveAspect", label: "Preserve Aspect", type: "boolean", defaultValue: true },
    ],
  }),
  defineNode({
    id: "layout-tile",
    name: "Tile Geometry",
    description: "Repeats patterns across a grid.",
    category: "layout",
    lane: "plot",
    maturity: "advanced",
    inputs: [{ id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "tiled", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "columns", label: "Columns", type: "integer", defaultValue: 3 },
      { id: "rows", label: "Rows", type: "integer", defaultValue: 3 },
      { id: "spacing", label: "Spacing", type: "vector2", defaultValue: { x: 10, y: 10 } },
    ],
  }),
  defineNode({
    id: "layout-mirror",
    name: "Mirror",
    description: "Reflects geometry across axes.",
    category: "layout",
    lane: "plot",
    maturity: "advanced",
    inputs: [{ id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "mirrored", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "axis", label: "Axis", type: "enum", defaultValue: "x", options: [
        { label: "Horizontal", value: "x" },
        { label: "Vertical", value: "y" },
        { label: "Radial", value: "radial" },
      ] },
    ],
  }),
  defineNode({
    id: "layout-array",
    name: "Array / Repeat",
    description: "Creates radial or grid repetitions.",
    category: "layout",
    lane: "plot",
    maturity: "advanced",
    inputs: [{ id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "arrayed", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "grid", options: [
        { label: "Grid", value: "grid" },
        { label: "Radial", value: "radial" },
      ] },
      { id: "count", label: "Count", type: "integer", defaultValue: 6 },
      { id: "radius", label: "Radius", type: "number", defaultValue: 200 },
    ],
  }),
  defineNode({
    id: "layout-crop-page",
    name: "Crop to Page",
    description: "Clips geometry outside page bounds.",
    category: "layout",
    lane: "plot",
    maturity: "mvp",
    inputs: [{ id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true }],
    outputs: [{ id: "polylines", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "page", label: "Page Preset", type: "enum", defaultValue: "letter-portrait", options: [
        { label: "Letter Portrait", value: "letter-portrait" },
        { label: "Letter Landscape", value: "letter-landscape" },
        { label: "Custom", value: "custom" },
      ] },
      { id: "width", label: "Width", type: "number", defaultValue: 215.9, unit: "mm" },
      { id: "height", label: "Height", type: "number", defaultValue: 279.4, unit: "mm" },
    ],
  }),
  defineNode({
    id: "layout-frame-guide",
    name: "Frame / Margin Guide",
    description: "Generates optional guide geometry for composition.",
    category: "layout",
    lane: "plot",
    maturity: "advanced",
    inputs: [],
    outputs: [{ id: "guides", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "page", label: "Page", type: "enum", defaultValue: "letter-portrait", options: [
        { label: "Letter Portrait", value: "letter-portrait" },
        { label: "A4 Portrait", value: "a4-portrait" },
      ] },
      { id: "margin", label: "Margin", type: "number", defaultValue: 10 },
    ],
  }),
  defineNode({
    id: "layout-compose-layers",
    name: "Compose Layers",
    description: "Combines multiple geometry branches into a layered document.",
    category: "layout",
    lane: "plot",
    maturity: "mvp",
    inputs: [
      { id: "inputs", label: "Geometry Inputs", kind: "PolylineSet", required: true, acceptsMultiple: true },
    ],
    outputs: [{ id: "layers", label: "LayeredGeometry", kind: "LayeredGeometry", required: true }],
    parameters: [],
  }),
  defineNode({
    id: "layout-mask-compose",
    name: "Mask Compose",
    description: "Uses one branch to clip another at the layout stage.",
    category: "layout",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "geometry", label: "Geometry", kind: "PolylineSet", required: true },
      { id: "mask", label: "Mask", kind: "Mask", required: true },
    ],
    outputs: [{ id: "masked", label: "PolylineSet", kind: "PolylineSet", required: true }],
    parameters: [
      { id: "mode", label: "Mode", type: "enum", defaultValue: "inside", options: [
        { label: "Inside", value: "inside" },
        { label: "Outside", value: "outside" },
      ] },
    ],
  }),
];
const layerNodes: NodeDefinition[] = [
  defineNode({
    id: "layer-assign",
    name: "Assign Layer",
    description: "Places geometry into named layers with pen metadata.",
    category: "layer",
    lane: "plot",
    maturity: "second-wave",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true },
    ],
    outputs: [
      { id: "layered", label: "LayeredGeometry", kind: "LayeredGeometry", required: true },
    ],
    parameters: [
      { id: "layerName", label: "Layer Name", type: "text", defaultValue: "Layer 1" },
      { id: "penName", label: "Pen Name", type: "text", defaultValue: "Pen A" },
      { id: "color", label: "Preview Color", type: "color", defaultValue: "#111111" },
    ],
  }),
  defineNode({
    id: "layer-split",
    name: "Split by Attribute",
    description: "Separates geometry by source, level, region, or pen assignment.",
    category: "layer",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "layered", label: "LayeredGeometry", kind: "LayeredGeometry", required: true },
    ],
    outputs: [
      { id: "layers", label: "LayeredGeometry", kind: "LayeredGeometry", required: true },
    ],
    parameters: [
      { id: "attribute", label: "Attribute", type: "enum", defaultValue: "source", options: [
        { label: "Source", value: "source" },
        { label: "Contour Level", value: "level" },
        { label: "Pen", value: "pen" },
      ] },
    ],
  }),
  defineNode({
    id: "layer-merge",
    name: "Merge Layers",
    description: "Combines multiple layer groups.",
    category: "layer",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "layers", label: "LayeredGeometry", kind: "LayeredGeometry", required: true, acceptsMultiple: true },
    ],
    outputs: [
      { id: "merged", label: "LayeredGeometry", kind: "LayeredGeometry", required: true },
    ],
    parameters: [],
  }),
  defineNode({
    id: "layer-recolor-preview",
    name: "Recolor Preview",
    description: "Adjusts preview colors without affecting SVG stroke metadata.",
    category: "layer",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "layered", label: "LayeredGeometry", kind: "LayeredGeometry", required: true },
    ],
    outputs: [
      { id: "recolored", label: "LayeredGeometry", kind: "LayeredGeometry", required: true },
    ],
    parameters: [
      { id: "palette", label: "Palette", type: "color", defaultValue: "#0f172a" },
    ],
  }),
  defineNode({
    id: "layer-stroke-preview",
    name: "Stroke Preview Settings",
    description: "Controls preview stroke width and opacity.",
    category: "layer",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "layered", label: "LayeredGeometry", kind: "LayeredGeometry", required: true },
    ],
    outputs: [
      { id: "styled", label: "LayeredGeometry", kind: "LayeredGeometry", required: true },
    ],
    parameters: [
      { id: "width", label: "Stroke Width", type: "number", defaultValue: 0.3 },
      { id: "opacity", label: "Opacity", type: "number", defaultValue: 1, min: 0, max: 1 },
    ],
  }),
];
const previewNodes: NodeDefinition[] = [
  defineNode({
    id: "preview-geometry-stats",
    name: "Geometry Stats",
    description: "Reports path count, point count, and travel metrics.",
    category: "preview",
    lane: "plot",
    maturity: "mvp",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true },
    ],
    outputs: [
      { id: "stats", label: "Stats", kind: "PlotStats", required: false },
    ],
    parameters: [],
  }),
  defineNode({
    id: "preview-field-histogram",
    name: "Field Histogram",
    description: "Visualizes field value distribution for tuning.",
    category: "preview",
    lane: "data",
    maturity: "advanced",
    inputs: [
      { id: "field", label: "ScalarField", kind: "ScalarField", required: true },
    ],
    outputs: [
      { id: "histogram", label: "PlotDocument", kind: "PlotDocument", required: false },
    ],
    parameters: [
      { id: "bins", label: "Bins", type: "integer", defaultValue: 32 },
    ],
  }),
  defineNode({
    id: "preview-bounds",
    name: "Bounds Analyzer",
    description: "Reports bounding boxes for geometry or fields.",
    category: "preview",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: false },
      { id: "field", label: "ScalarField", kind: "ScalarField", required: false },
    ],
    outputs: [
      { id: "bounds", label: "BoundingBox", kind: "BoundingBox", required: true },
    ],
    parameters: [],
  }),
  defineNode({
    id: "preview-intersections",
    name: "Intersection Analyzer",
    description: "Detects dense crossings and overlaps.",
    category: "preview",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true },
    ],
    outputs: [
      { id: "report", label: "PlotDocument", kind: "PlotDocument", required: false },
    ],
    parameters: [
      { id: "threshold", label: "Threshold", type: "number", defaultValue: 10 },
    ],
  }),
  defineNode({
    id: "preview-plot-time",
    name: "Plot Time Estimator",
    description: "Estimations for runtime using machine assumptions.",
    category: "preview",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true },
    ],
    outputs: [
      { id: "report", label: "PlotDocument", kind: "PlotDocument", required: false },
    ],
    parameters: [
      { id: "machine", label: "Machine Preset", type: "enum", defaultValue: "axidraw", options: [
        { label: "AxiDraw", value: "axidraw" },
        { label: "iDraw", value: "idraw" },
        { label: "Custom", value: "custom" },
      ] },
      { id: "penUpSpeed", label: "Pen-up Speed", type: "number", defaultValue: 300 },
      { id: "penDownSpeed", label: "Pen-down Speed", type: "number", defaultValue: 120 },
    ],
  }),
];
const outputNodes: NodeDefinition[] = [
  defineNode({
    id: "output-svg",
    name: "SVG Output",
    description: "Serializes geometry into downloadable SVG documents.",
    category: "output",
    lane: "plot",
    maturity: "mvp",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: false },
      { id: "layers", label: "LayeredGeometry", kind: "LayeredGeometry", required: false },
    ],
    outputs: [
      { id: "document", label: "PlotDocument", kind: "PlotDocument", required: true },
    ],
    parameters: [
      { id: "page", label: "Page Size", type: "enum", defaultValue: "letter-portrait", options: [
        { label: "Letter Portrait", value: "letter-portrait" },
        { label: "Letter Landscape", value: "letter-landscape" },
        { label: "A4 Portrait", value: "a4-portrait" },
        { label: "A4 Landscape", value: "a4-landscape" },
      ] },
      { id: "units", label: "Units", type: "enum", defaultValue: "mm", options: [
        { label: "Millimeters", value: "mm" },
        { label: "Inches", value: "in" },
      ] },
      { id: "groupLayers", label: "Group Layers", type: "boolean", defaultValue: true },
      { id: "title", label: "Document Title", type: "text" },
      { id: "precision", label: "Precision", type: "integer", defaultValue: 3 },
    ],
  }),
  defineNode({
    id: "output-preview",
    name: "Plot Preview",
    description: "Renders final linework in the viewer.",
    category: "output",
    lane: "plot",
    maturity: "second-wave",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: false },
      { id: "layers", label: "LayeredGeometry", kind: "LayeredGeometry", required: false },
    ],
    outputs: [
      { id: "preview", label: "PlotDocument", kind: "PlotDocument", required: false },
    ],
    parameters: [
      { id: "background", label: "Background Color", type: "color", defaultValue: "#050608" },
      { id: "strokeWidth", label: "Preview Stroke Width", type: "number", defaultValue: 0.25 },
      { id: "showTravel", label: "Show Travel", type: "boolean", defaultValue: false },
    ],
  }),
  defineNode({
    id: "output-json",
    name: "JSON Project Output",
    description: "Serializes graph or geometry state.",
    category: "output",
    lane: "global",
    maturity: "advanced",
    inputs: [
      { id: "document", label: "PlotDocument", kind: "PlotDocument", required: true },
    ],
    outputs: [
      { id: "json", label: "Any", kind: "Any", required: true },
    ],
    parameters: [
      { id: "pretty", label: "Pretty Print", type: "boolean", defaultValue: true },
    ],
  }),
  defineNode({
    id: "output-gcode",
    name: "G-code Output",
    description: "Optional export for CNC or pen plotters supporting G-code.",
    category: "output",
    lane: "plot",
    maturity: "advanced",
    inputs: [
      { id: "geometry", label: "PolylineSet", kind: "PolylineSet", required: true },
    ],
    outputs: [
      { id: "gcode", label: "Any", kind: "Any", required: true },
    ],
    parameters: [
      { id: "machine", label: "Machine Preset", type: "enum", defaultValue: "generic", options: [
        { label: "Generic", value: "generic" },
        { label: "AxiDraw (via VPype)", value: "axidraw" },
      ] },
      { id: "feedRate", label: "Feed Rate", type: "number", defaultValue: 1200 },
    ],
  }),
];
const utilityNodes: NodeDefinition[] = [
  defineNode({
    id: "util-number",
    name: "Number",
    description: "Outputs numeric constants.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [],
    outputs: [{ id: "value", label: "Number", kind: "Number", required: true }],
    parameters: [
      { id: "value", label: "Value", type: "number", defaultValue: 1 },
    ],
  }),
  defineNode({
    id: "util-vector2",
    name: "Vector2",
    description: "Outputs 2D vectors.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [],
    outputs: [{ id: "value", label: "Vector2", kind: "Vector2", required: true }],
    parameters: [
      { id: "x", label: "X", type: "number", defaultValue: 0 },
      { id: "y", label: "Y", type: "number", defaultValue: 0 },
    ],
  }),
  defineNode({
    id: "util-color",
    name: "Color",
    description: "Outputs color metadata for preview/layers.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [],
    outputs: [{ id: "color", label: "Color", kind: "Color", required: true }],
    parameters: [
      { id: "color", label: "Color", type: "color", defaultValue: "#ffffff" },
    ],
  }),
  defineNode({
    id: "util-seed",
    name: "Seed",
    description: "Supplies deterministic random seeds to downstream nodes.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [],
    outputs: [{ id: "seed", label: "Seed", kind: "Seed", required: true }],
    parameters: [
      { id: "seed", label: "Seed Value", type: "text", defaultValue: "plotter" },
      { id: "lock", label: "Lock Seed", type: "boolean", defaultValue: true },
    ],
  }),
  defineNode({
    id: "util-range",
    name: "Range",
    description: "Outputs numeric lists for contour or band selection.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [],
    outputs: [{ id: "values", label: "Number", kind: "Number", required: true }],
    parameters: [
      { id: "start", label: "Start", type: "number", defaultValue: 0 },
      { id: "end", label: "End", type: "number", defaultValue: 1 },
      { id: "steps", label: "Steps", type: "integer", defaultValue: 5 },
    ],
  }),
  defineNode({
    id: "util-switch",
    name: "Switch",
    description: "Chooses between inputs via condition.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [
      { id: "condition", label: "Condition", kind: "Boolean", required: false },
      { id: "a", label: "Input A", kind: "Any", required: true },
      { id: "b", label: "Input B", kind: "Any", required: true },
    ],
    outputs: [{ id: "output", label: "Any", kind: "Any", required: true }],
    parameters: [],
  }),
  defineNode({
    id: "util-mix",
    name: "Mix",
    description: "Interpolates between values or fields.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [
      { id: "a", label: "Input A", kind: "Any", required: true },
      { id: "b", label: "Input B", kind: "Any", required: true },
      { id: "t", label: "Mix", kind: "Number", required: false },
    ],
    outputs: [{ id: "mixed", label: "Any", kind: "Any", required: true }],
    parameters: [
      { id: "factor", label: "Factor", type: "number", defaultValue: 0.5 },
    ],
  }),
  defineNode({
    id: "util-compare",
    name: "Compare / Logic",
    description: "Performs thresholding or boolean checks.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [
      { id: "input", label: "Input", kind: "ScalarField", required: false },
      { id: "value", label: "Value", kind: "Number", required: false },
    ],
    outputs: [
      { id: "mask", label: "Mask", kind: "Mask", required: false },
      { id: "boolean", label: "Boolean", kind: "Boolean", required: false },
    ],
    parameters: [
      { id: "operator", label: "Operator", type: "enum", defaultValue: ">", options: [
        { label: ">", value: ">" },
        { label: "<", value: "<" },
        { label: ">=", value: ">=" },
        { label: "<=", value: "<=" },
      ] },
      { id: "threshold", label: "Threshold", type: "number", defaultValue: 0.5 },
    ],
  }),
  defineNode({
    id: "util-randomizer",
    name: "Randomizer",
    description: "Produces repeatable random values from a seed.",
    category: "utility",
    lane: "global",
    maturity: "advanced",
    inputs: [
      { id: "seed", label: "Seed", kind: "Seed", required: false },
    ],
    outputs: [
      { id: "value", label: "Number", kind: "Number", required: true },
    ],
    parameters: [
      { id: "min", label: "Min", type: "number", defaultValue: 0 },
      { id: "max", label: "Max", type: "number", defaultValue: 1 },
    ],
  }),
];
const macroNodes: NodeDefinition[] = [
  defineNode({
    id: "macro-generic",
    name: "Macro Node",
    description: "Wraps multiple nodes into a reusable module.",
    category: "macro",
    lane: "global",
    maturity: "advanced",
    inputs: [
      { id: "inputs", label: "Inputs", kind: "Any", required: false, acceptsMultiple: true },
    ],
    outputs: [
      { id: "outputs", label: "Outputs", kind: "Any", required: false, acceptsMultiple: true },
    ],
    parameters: [
      { id: "name", label: "Macro Name", type: "text" },
      { id: "description", label: "Description", type: "text" },
    ],
    tags: ["topographic from noise", "image to clean contours", "radial waveform ring", "plotter safe cleanup"],
  }),
  defineNode({
    id: "macro-preset",
    name: "Preset Pipeline",
    description: "Curated compound node for beginners.",
    category: "macro",
    lane: "global",
    maturity: "advanced",
    inputs: [
      { id: "inputs", label: "Inputs", kind: "Any", required: false, acceptsMultiple: true },
    ],
    outputs: [
      { id: "outputs", label: "Outputs", kind: "Any", required: false, acceptsMultiple: true },
    ],
    parameters: [
      { id: "preset", label: "Preset", type: "enum", defaultValue: "image-contours", options: [
        { label: "Image Contours", value: "image-contours" },
        { label: "Noise Terrain", value: "noise-terrain" },
        { label: "Audio Wave Ring", value: "audio-wave-ring" },
        { label: "Hatch from Brightness", value: "hatch-brightness" },
      ] },
    ],
  }),
];

const allNodes: NodeDefinition[] = [
  ...sourceNodes,
  ...conversionNodes,
  ...fieldNodes,
  ...vectorFieldNodes,
  ...audioNodes,
  ...geometryNodes,
  ...pathNodes,
  ...optimizationNodes,
  ...layoutNodes,
  ...layerNodes,
  ...previewNodes,
  ...outputNodes,
  ...utilityNodes,
  ...macroNodes,
];

export const nodeList = allNodes;

export const nodeLibrary: NodeLibrary = allNodes.reduce<NodeLibrary>((acc, node) => {
  acc[node.id] = node;
  return acc;
}, {});
